### ISSUE TITLE
Configure Offline use

### ISSUE THREAD

**Issue by naftalimurgor** [camposFabio/flutter_handbook#1]
Hey I'd like to configure this gitbook for offline use. I need your assistance. Thanks

**Comment by wuhaohao1234** [comment]
You can view the commit record, first clone the code, and then switch to different commit IDs through git, and the page viewed on the Android emulator can be summarized into a document

**Comment by naftalimurgor** [comment]
Thanks, I will update the documentation and submit a pull request for that.
